name: CD to Azure App Service

on:
  workflow_run:
    workflows: ["CI (.NET)"]
    types: [completed]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout source at triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish API artifact
        run: dotnet publish src/Calculator.Api/Calculator.Api.csproj -c Release -o ./publish

      - name: Show publish output (sanity check)
        run: |
          echo "Contents of ./publish:"
          ls -la ./publish
          echo "Assemblies under publish:"
          find ./publish -maxdepth 2 -type f -name "*.dll" -print
          test -f "./publish/Calculator.Api.dll"

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.MYWEBAPI_POC }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish

      - name: Health check with retries
        env:
          HOST: ${{ secrets.MYWEBAPI_POC }}
        run: |
          set -e
          URL="https://${HOST}.azurewebsites.net/health"
          echo "Checking $URL ..."
          # Espera y reintenta hasta 2 minutos
          for i in $(seq 1 24); do
            CODE=$(curl -sSk -o /dev/null -w "%{http_code}" -L "$URL" || true)
            if [ "$CODE" = "200" ]; then
              echo "✅ Health OK (HTTP 200)"; exit 0
            fi
            echo "Attempt $i: got HTTP $CODE, retrying..."
            sleep 5
          done
          echo "❌ Health did not return 200 within the timeout. Dumping response:"
          curl -sSk -L "$URL" || true
          exit 1

